# GitHub Pages 配置
title: 存贷组合产品测算器
description: 专业的存贷组合产品测算工具，帮您计算最优的金融方案
baseurl: ""
url: ""

# 插件
plugins:
  - jekyll-sitemap
  - jekyll-feed

# 排除文件
exclude:
  - README.md
  - LOCAL-DEVELOPMENT.md
  - src-structure-rules.md
  - 需求文档/
  - .specstory/
  - .vscode/
  - .playwright-mcp/
  - tmp/
  - netlify.toml
  - package-lock.json

# 包含文件
include:
  - page/
  - src/
  - wechat.html
  - redirect.html
  - mobile-demo.html
  - standalone-demo.html
